<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Chess.Logic\Chess.Logic.csproj" />
        <ProjectReference Include="..\Chess.Dal\Chess.Dal.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="Chess.Api.Tests" />
    </ItemGroup>

</Project>
